all:
  vars:
    ansible_connection: ssh
    ansible_user: developer
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

zookeeper:
  hosts:
    10.2.2.4:
      internal_ip: 10.2.2.4
    10.2.2.5:
      internal_ip: 10.2.2.5
    10.2.2.6:
      internal_ip: 10.2.2.6
kafka_broker:
  hosts:
    10.2.2.4:
    10.2.2.5:
    10.2.2.6:

schema_registry:
  hosts:
    10.2.2.4:
control_center:
  hosts:
    10.2.2.5:
