all:
  vars:
    ansible_connection: ssh
    ansible_user: developer
    ansible_become: true
    ansible_ssh_private_key_file: covid19app.pem

zookeeper:
  hosts:
    10.1.0.4:
      internal_ip: 10.1.0.4
    10.1.0.5:
      internal_ip: 10.1.0.5
    10.1.0.6:
      internal_ip: 10.1.0.6
kafka_broker:
  hosts:
    10.1.0.4:
    10.1.0.5:
    10.1.0.6:

schema_registry:
  hosts:
    10.1.0.4:
control_center:
  hosts:
    10.1.0.5:
